### ISSUE TITLE
How to use initialValue?

### ISSUE THREAD

**Issue by ElanErlangga** [amirr-dotcom/custom_searchable_dropdown#2]
Hello, I'm a beginner user of this plugin, i want to use initialValue but i dont know how to use it.
I have tried this way :

`initialValue: listToSearch.map((e) {
    return int.parse(e['class'] = '12');
 toList(),` or
`initialValue: listToSearch.map((e) {
    return e['name'] = 'Amir';
 toList(),`

but the result is error like this:

`Class 'int' has no instance method '[]'.`
`Receiver: 12`
`Tried calling: []("id")` or
`type 'String' is not a subtype of type 'int' of 'index'`

Thank you;

**Comment by amirr-dotcom** [comment]
initialValue: [
                          {
                            'param': 'name',
                            'id': 'Amir'
                          }
                        ],


You need to use it like this

In param you need to give parameter name from which you are picking up the
value

In id you need to give that name or id which is stored in this parameter

Initial value is used to show initial first value in dropdown you need to
clear that value if you want to use different one

Just add
Param   parameter name
Id data stored in that parameter which you want initially

**Comment by ElanErlangga** [comment]
Thank you very much. its work.
