### ISSUE TITLE
menu mode layout overflow

### ISSUE THREAD

**Issue by NoNSteP** [amirr-dotcom/custom_searchable_dropdown#6]
Hi!
I'm starting to use your widget and I'm really enjoying it.
When i use menu mode  i want to lock position of CustomSearchableDropDown widget but when i search item list item area size of widget change and overflow . Can i edit item search area to front layer for lock position widget.
or Can i change showDialogueBox height and width.
![image](https://user-images.githubusercontent.com/84696880/144036364-b3a2e086-1204-4db0-bc09-5feb9264d0c7.png)
![image](https://user-images.githubusercontent.com/84696880/144036904-e1b3b5df-18df-49d8-9d1c-a5811fc8b644.png)
sorry for my bad english.
Thank you.

**Comment by amirr-dotcom** [comment]
Can You Send me the code so that i can check why its happening or if i can
fix it, and please send version of custom searchable dropdown you are using

**Comment by amirr-dotcom** [comment]
Can i edit item search area to front layer for lock position widget.

for this you can give the height of menu
but the csd is made for a scrollable screen so avoid using it in a
container with a static height
and send me the complete code of this page so i can take a look to it.

**Comment by NoNSteP** [comment]
sorry to let you wait.
i use in container with fix height.
so i should use popup mode right, can i edit popup width, i made program for web.
Thank you very much.

`import 'package:custom_searchable_dropdown/custom_searchable_dropdown.dart';
import 'package:flutter/material.dart';
//--------------------------------------------- Bloc

//---------------------------------------------
import 'package:flutter/rendering.dart';
import 'dart:ui';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.purple,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: test(),
    );
  }
}

class test extends StatelessWidget {
  test({Key? key}) : super(key: key);
  final item = [
    {"Jack", 23},
    {"Adam", 27},
    {"Katherin", 25}
  ];
  TextStyle stylesection =
      TextStyle(fontSize: 13, fontWeight: FontWeight.bold, fontFamily: 'Mitr');
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("widget.title"),
        ),
        body: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Container(
              width: 600,
              height: 280,
              child:
                  Column(mainAxisAlignment: MainAxisAlignment.start, children: [
                Center(
                    child: Container(
                        width: 600,
                        height: 280,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.all(Radius.circular(0)),
                          color: Colors.white,
                          boxShadow: [
                            BoxShadow(
                                offset: Offset(0, 0),
                                blurRadius: 10,
                                spreadRadius: 0)
                          ],
                        ),
                        child: Column(
                            mainAxisAlignment: MainAxisAlignment.start,
                            children: [
                              Container(
                                  decoration: BoxDecoration(
                                    borderRadius:
                                        BorderRadius.all(Radius.circular(0)),
                                    color: Colors.grey,
                                  ),
                                  height: 100,
                                  child: Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.start,
                                      children: <Widget>[
                                        Container(
                                          width: 200,
                                          child: Text(
                                            "CUSTOMER",
                                            style: stylesection,
                                          ),
                                        ),
                                        Container(
                                            width: 300,
                                            child: CustomSearchableDropDown(
                                                primaryColor: Colors.black,
                                                menuMode: true,
                                                labelStyle: stylesection,
                                                menuHeight: 100,
                                                items: item,
                                                label: 'SELECT CUSTOMER',
                                                prefixIcon: Padding(
                                                  padding:
                                                      const EdgeInsets.all(0.0),
                                                  child: Icon(Icons.search),
                                                ),
                                                dropDownMenuItems: item,
                                                onChanged: (value) {}))
                                      ]))
                            ])))
              ]),
            )));
  }
}
`
and version is custom_searchable_dropdown: ^2.0.9

**Comment by amirr-dotcom** [comment]
I have Added The menPadding in version 2.1.0
use this version to add padding in your menu

**Comment by amirr-dotcom** [comment]
if u can just removes height from

Container(
decoration: BoxDecoration(
borderRadius:
BorderRadius.all(Radius.circular(0)),
color: Colors.grey,
),
*height: 100,*
child: Row(
mainAxisAlignment:
MainAxisAlignment.start,
children: [
Container(
width: 200,
child: Text(
"CUSTOMER",
style: stylesection,
),
),

this code

itll fix the issue and then you can run it in memu mode.

**Comment by NoNSteP** [comment]
Thank you very much.

**Comment by amirr-dotcom** [comment]
No issue please be sure to give suggestions again so that i can improve it
more.

Thankyou..
