### ISSUE TITLE
Multi Select as Widget Initial Value not working

### ISSUE THREAD

**Issue by sucurovicd** [amirr-dotcom/custom_searchable_dropdown#7]
Hi,
First of all thank you for this plugin, it really is what I need for my project and it is saving me a lot of time.

I am having one problem, I have implement Multi Select as widget, and choosing an option is working as it should.
Problem is with initial value, I have tried multiple ways to implement it, but without success. 

I have checked your code, line 100-102:

 ```
        if(widget.initialValue[0]['id']==widget.items[i][widget.initialValue[0]['param']]){
          onSelectLabel=widget.dropDownMenuItems[i].toString();
        }
 ```

It looks like you are checking only first index of initialValue and not others.
Thank you,
Darko

**Comment by amirr-dotcom** [comment]
Ok i will fix it i made it only for the single select but i will surely fix
it as soon as possible and get back to you thankyou fir the suggestion i
will surely make the changes.

And do keeping on making suggestion like that so that i can improve the
dependency

**Comment by amirr-dotcom** [comment]
Fixed the issue

please use custom_searchable_dropdown: ^2.1.1
 it contains new updated code now you can give multiple values in Initial
Value.
Please refer to the example some parameter names are also changed so please
refer to documents and example

**Comment by sucurovicd** [comment]
Thank you very much for this fast response and update.
I haven't dreamed that you will fix this so soon :)

**Comment by amirr-dotcom** [comment]
No problem and thank you for the suggestion
And keep suggesting imorovement so that i can make it better than it is
now.

Thankyou
